services:
  opaws:
    container_name: opaws
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./opa-ws:/opa-ws
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
    networks:
      - my-network
  psql:
    container_name: psql
    image: postgres:16.4-alpine3.20
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    ports:
      - 5432:5432
    networks:
      - my-network

networks:
  my-network: